import type { Metadata } from 'next'
import { Caveat, Kanit, Lato, Lustria } from 'next/font/google'
import './globals.css'
import RootLayoutWrapper from './root-layout'

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900']
})

const lustria = Lustria({
  variable: '--font-lustria',
  subsets: ['latin'],
  weight: ['400']
})

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

const caveat = Caveat({
  variable: '--font-caveat',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-[#fcf7f2] dark:bg-black text-[#171717] dark:text-[#ededed] ${lato.variable} ${lustria.variable} ${kanit.variable} ${caveat.variable} antialiased`}
      >
        <RootLayoutWrapper>{children}</RootLayoutWrapper>
      </body>
    </html>
  )
}
